### ISSUE TITLE
两件事情

### ISSUE THREAD

**Issue by langren1353** [dupontjoy/userChrome.js-Collections-#1]
1. 为什么要干掉学习图片呢，我觉得我们要好好学习
2. 能不能原生的加一个扩展进去啊~~地址：https://addons.mozilla.org/zh-CN/firefox/addon/ACMMize/
求支持，求推广，一切为了firefox             -。-!!

**Comment by dupontjoy** [comment]
1. 新增了几个教程
2. ACMMize我没有需要用到的场景
