### ISSUE TITLE
提示

### ISSUE THREAD

**Issue by candy2107** [dupontjoy/userChrome.js-Collections-#6]
能否基于 firefox esr 版制作一个包
firefox从57开始好多插件失效，而esr版没事

**Comment by dupontjoy** [comment]
已转Nightly了, 虽有web版目前支持不足, 但实际用起来还是不错的
以前的UC脚本都丢掉了, 其实也没有太大的不适

ESR的话, 其实不用改, 原来的配置包就可以用的, 自行升级一下Firefox程序就好
