### ISSUE TITLE
cingfox

### ISSUE THREAD

**Issue by kmsda187** [dupontjoy/userChrome.js-Collections-#8]
hey, great just great mod, using it daily
but updated to latest 61a1 nightly and userchromeJS menu died :(
then tried downgrading to 60b6-b8 both dead too, but some .uc.js still work, but no menu in nav-bar and none in about:addons (like the one you have on a screenshot near the Addons, Themes...)

btw @alice0775 updated recently her UserchromeJS if it helps..
https://raw.githubusercontent.com/alice0775/userChrome.js/master/userChrome.js

also contextsearcher.user.js doesnt seems to be working, only in about:support :\
and some others, but i stick to minimalistic
only whats needed not to overload memory

anyway just a thumbs up post to keep your GREAT WORK!
thank you very much! much appreciated!

**Comment by dupontjoy** [comment]
Thanks 
but I have removed all UC scripts since upgrading to 57+ quantum last october
